### ISSUE TITLE
Duplicate item review

### ISSUE THREAD

**Issue by ArtOfCode-** [CrowdRescueHQ/SCOT#47]
We need a way to track down and remove (deactivate) any items that are duplicates of those already entered.

 - [ ] When an item is submitted, if it has *identical* text to another item that already exists, ask the user to confirm that they want to submit it again.
 - [ ] Add a way to find *similar* texts - not identical, but there are a number of items that say the same thing that also need to be deactivated.

**Comment by izwick-schachter** [comment]
To include some info from #60, we should have deduplication on submission of broadcast items and of rescue requests.

**Comment by izwick-schachter** [comment]
Partially solved (checkbox 1) by #86

**Comment by ArtOfCode-** [comment]
**&rarr;** #86
