### ISSUE TITLE
Pagination is broken

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/SCOT#68]

**Comment by ArtOfCode-** [comment]
define broken?

**Comment by izwick-schachter** [comment]
CSS broken. I would attach a screenshot, but GH got angry.

**Comment by izwick-schachter** [comment]
![screenshot from 2017-10-10 19-39-30](https://user-images.githubusercontent.com/15304293/31417975-18356726-ae01-11e7-8043-04b9b1aa0485.png)

**Comment by ArtOfCode-** [comment]
Ah, yeah. I guess `will_paginate-bootstrap` hasn't been updated for Bootstrap 4 then.

**Comment by izwick-schachter** [comment]
See bootstrap-ruby/will_paginate-bootstrap/issues/45

**Comment by ArtOfCode-** [comment]
or just use https://github.com/delef/will_paginate-bootstrap4
