### ISSUE TITLE
Pull "source" info and output to spreadsheet

### ISSUE THREAD

**Issue by MeghanUX** [CrowdRescueHQ/SCOT#71]
@ArtOfCode- Create the ability to "pull" data from the Broadcast "Source" data. Each day, pull all the "new" sources and output to a google spreadsheet on our drive. Obviously, the first pull will include - everything up to today's date. Even better - output two columns - one for "source" and one for "Region / Municipality". Add pull date - "somewhere" (tab name?)

**Comment by izwick-schachter** [comment]
This is infeasible, unless @ArtOfCode- has other ideas?

**Comment by ArtOfCode-** [comment]
Totally feasible, but perhaps not advisable in terms of performance. We could supply a CSV API, though, if that would suit - @MeghanUX?

**Comment by izwick-schachter** [comment]
Removing status-declined because we can build CSV export.

**Comment by ArtOfCode-** [comment]
If this isn't an urgent need, it can happen as part of #102

**Comment by ArtOfCode-** [comment]
Merging into #102.
