### ISSUE TITLE
Integration translations into broadcast

### ISSUE THREAD

**Issue by MeghanUX** [CrowdRescueHQ/SCOT#72]
To avoid getting Translation requests that belong in Broadcast. let's change the text on the Translations New page.

OLD
**Content**. What needs translating? Either paste the text here, or a link to the item that needs translation.

NEW
**Content**.  If this is a BROADCAST translation request, please do NOT use this form. All other items needing translation - paste the text or a link to the item in this box.

**Comment by izwick-schachter** [comment]
I think we can expand this to be a way to link translation requests to broadcast items. That way, when a broadcast item is created, a user can create a translation request on it, and translators won't have to track both the "Needs translation" page in broadcast and then "Needs translation" page in translations.

**Comment by ArtOfCode-** [comment]
Completed by 7e50931e50501f48f6a4da81c2875d55f461ba25

**Comment by izwick-schachter** [comment]
I mean that it needs to be fully integrated, not just this linky functionality

**Comment by ArtOfCode-** [comment]
Define "integrated"?

**Comment by izwick-schachter** [comment]
Each broadcast item should `have_many :translations`, and all the UI should reflect that.

**Comment by MeghanUX** [comment]
If I understand, then yes - Translators should get a single "needs translation" list, that they can sort as they wish. Which also indicates ultimate destination(s). So if an item is intended for broadcast - it will say that. And if for Broadcast AND also to use in a graphic. It will say that. YES.

**Comment by MeghanUX** [comment]
My other concern is on the INPUT end. We have a task-flow for Broadcast, that has two content fields. We don't want ppl to then go over to Translation - and put the request in AGAIN as a separate translation request. Because it's already handled on the Broadcast input page automatically. so, the "Request Translation" should somehow indicate to the REQUESTORS - "stop, don't put Broadcast translation requests here, because it's automatic when you create a new broadcast item" - but in better English.

**Comment by ArtOfCode-** [comment]
@izwick-schachter Why `has_many`? You're only going to need to translate one way, surely? At the moment, a broadcast item `belongs_to` a translation, and translation `has_many` broadcast items.

**Comment by MeghanUX** [comment]
On the "Edit Broadcast Item" page...
As we change the original Input page, we should keep the associated Edit page in sync.

One way - just somehow link the text - so changes in the original are just re-displayed on the Edit page???

Otherwise, I suggest this wording change

**Original.**
1. Content Required. The English version of the post you're working on.
2. Translation Optional. Enter the Spanish translation of your post here.

**SUGGESTED**
1. CONTENT. English
2. CONTENT. Spanish

**Comment by MeghanUX** [comment]
And while we are on this page, can you fix the format for the Day/Time?

**Original**
2017-10-13T19:19:03Z

**Suggested**
2017-10-13, 19:19:03 <timezone>
[note spaces and use of punctuation)

Where "timezone" indicates BOTH - 3 letter code and common name. And please, no military or jargon terms (like Zulu time).

Like this:
EST - Eastern Standard Time
AST - Atlantic Standard Time

Or even this:
EST - Eastern Standard Time (UTC-04:00)
AST - Atlantic Standard Time (UTC-04:00)

**Comment by MeghanUX** [comment]
oops, the above is missing this line:

2017-10-10, 19:19:25 <timezone>

**Comment by ArtOfCode-** [comment]
I don't think we *can* fix the time format, actually. I know it's not the best format for users, but - IIRC - it's required by our datepicker plugin to be in that format. If we're lucky, it might be possible to do some clever scripting and hack it into the right format, but that needs more substantive work on it. Can you do me a separate issue for that, @MeghanUX, and I'll have a look at it when I'm back next week?

**Comment by Tensibai** [comment]
Maybe a silly idea, but couldn't it be 'updated' to a more readable format at display by a JS hook? Keeping the ISO format in requests, just reformatting at display, falling back to Original ISO in case of problem within the JS

**Comment by MeghanUX** [comment]
Tensibal sounds good. I don't speak code. Even just inserting spaces makes it more human readable.
Side note - I am incredibly crappy at "just insert it into..." or "make a new issue..." Luddite. Learning. Hey, I can now "Comment"! Inside GitHub! Progress!

**Comment by izwick-schachter** [comment]
The problem is that it's created by a JS library, so we'd have to modify that library which could be a lot of work for very little return.

**Comment by izwick-schachter** [comment]
Also @MeghanUX please don't just other things into this issue. If you want another thing fixed, please make a new issue.
