### ISSUE TITLE
Translation requests - change "my requests" to "request status" or similar

### ISSUE THREAD

**Issue by MeghanUX** [CrowdRescueHQ/SCOT#73]
In the Translation queue (pull-down) for item #2 "My requests", can this go to a general status page instead? Let's say I ask personX to submit a request for me. I'd still like to know it's status. So let's just have one big ol' page with all of the statuses on it. Then on the Status page, I would also like a filter.

Also, the use of "me, my" and "you" - is very confusing because of the different roles. For example, as a translator, I will want to open "my requests" to find out which ones have been assigned to "me". 

Here's my suggestion...

New menu
- New Request
- Status - All Requests
- Unassigned

On "Status - All Requests" page - these filter/sort options:
- date submitted
- ID number
- who submitted it
- from language
- to language
- who translated it (or, who it is assigned to)
- status (pending, completed, unassigned, ...)

**Comment by izwick-schachter** [comment]
Are you just suggesting we rename the current menu options and add some columns to the table?

**Comment by MeghanUX** [comment]
**Update**. I some changes have been made already (yeah!), so now updating the issue.

Menu - there are now 4 choices in there, and they are fine and resolve the menu issue, except this small wording change.

 Menu Item "open requests" --> "unassigned requests"
--------------------------
**Pages**
===============
** New Request**
1. Note the new request has these fields - and they should show up in columns / info on ALL other pages related to this request.
 - Content
- Source Language
- Target Language
- Deliver To
- Priority
- Due Date

2. Please change the "Priority" categories to match these (and we need to check with Translation about these definitions) - ALSO - if these categories are changed EVER, they also need to be changed on the other pages as well.
  "1=  Immediately (< 2 hours), 2 = Urgent (2-4 hours). 3= Today (before end of day) , 4= As possible"

3. Also add: "Cancel" button
----------------------------------------------
**My Translation Requests**
1. Change Title to: Translation Requests
1a. Change the description content...

  _Original_ - "This is a list of translation requests that you have submitted. You can use this to track the status of your requests."

 _New Description_ - "This is a list of translation requests that have been submitted. 
         Priority Codes - 1=  Immediately (< 2 hours), 2 = Urgent (2-4 hours). 
         3= Today (before end of day) , 4= As possible"

2. Show ALL Requests (not just mine) - because people often are tracking the progress of requests submitted by people who are not them, and it's good for them to see - how many OTHER requests are also in the queue, not just their own - as this will stop them from trying to escalate (and may even get them to lower priority, change channel, ...).

3. Column changes...

 Col 1 - ID - no change
 Col 2 - [NEW] Requestor name (sorted with "mine" on top, then by priority underneath)
            --> "Completed" items should drop out of this list after one week (let's check this amount of time with Translators, but let's start with "one week" and see how it goes)
 Col 3 - Content (fairly wide column) that shows on TWO rows, the source content on the top and the target language underneath (if not yet translated, the destination content area will be be blank/empty)
 Col 4 - [was "language"] change column title to: "Source / Target"
          Display - in top row -- source language name (e.g. English), as a hyperlink
                       - on bottom row - destination language name (e.g., Spanish), as a hyperlink
   --> clicking either of the language hyperlinks will take you to the page with the content / translation (thus eliminating the View Translation column and links)
  --> if we can't display these on two rows, then display this way "SourceLangName / TargetLangName", each name as a hyperlink.

Col 4 - Assigned to (no change) - if possible, can we use their Slack name?

 Col 5 - [NEW] Deliver to

 Col 6 - [NEW] Due - list info pulled from request. We can use this format "2017-10-25"

Col 7 -  Status - no change [note, this was previously col 5]

Col 8 - Priority - replace the words with numbers, (add a legend to the description area with explanation for each of the number). This should be sortable - (i.e., If i click on Priority, all the 1s show first, then the 2s, ...) BUT, it will always list "mine" at the top (i.e. Mine will sort by Priority at the top, followed by all the rest, sorted by Priority) [note, this was previously col 6]

 Col 9 - use the cute pencil icon you are using elsewhere - if clicked, this will take them back to their original request, with all details filled in. This will let them EDIT their original request. (this is a good chance for them to ie. change the destination or priority or...) Pencil ONLY shows up to requests they have personally made.

 Col  - [was "View Translation] - remove

---------------------------------
**Open Translation Requests**
1. Please see the column changes (including the pencil icon for requests made by "me") and change these columns to match, as appropriate

2. Can "Actions" be a pull-down menu and NOT take you to a different page?
2a. Presumably "Edit" is for the Requestor and not the translators? If yes, then remove from the Actions pull-down and use the pencil icon - as described above.
  Presumably only official "Translators" and/or Translation leads actually see the "Actions" menu??

3. If we can't get Actions to be a pull-down menu, then please add to this page these buttons
   -  "Return to Unassigned Requests Page"
  - "Cancel"

--------------------------------------
**Assigned to Me***

Please add the column changes described above, as appropriate.

THANKS!
MeghanUX

**Comment by izwick-schachter** [comment]
@MeghanUX Can you please make new issues for the new requests?

**Comment by MeghanUX** [comment]
Shall I do it at the "page" level?

**Comment by izwick-schachter** [comment]
Sure

**Comment by ArtOfCode-** [comment]
If I could, I would willingly include every field we have in the database in every table. However, once you go over about 5-6 columns, _especially_ if any of them are lengthy, there just isn't enough space on a screen. This is coming from a guy with a big screen, too, so I can imagine it's only worse on smaller screens or mobile.

I'm quite happy to _change_ some of the info that's in the table, if there are more important fields we could be showing instead, but I don't want to add any additional columns - that's what the details view is for.

**Comment by izwick-schachter** [comment]
I'm splitting this into smaller issues, to make it more easy to complete.
