### ISSUE TITLE
Add notes to broadcast items

### ISSUE THREAD

**Issue by MeghanUX** [CrowdRescueHQ/SCOT#83]
As individual items are reviewed, fact-checked, copy-edited and translated - there is meta-information generated. 

For example - this item represents a combination of former IDs 5, 6, 7, 8. Or, this has been fact-checked and the address updated to match X list. Or this item was translated using Google translate and needs to be updated. Or - I'm still fact-checking this item - please do NOT broadcast until I can confirm key details.

A generic open text-field box for Notes would be appreciated. This should follow the item from "New" through "Edit". For the moment, not into broadcast. Any table that lists the item should have a "Notes" column with a simple link that allows readers to read the Note (would be nice as a pop-up, rather than taking them to a new page). Notes are NOT for external viewing (e.g., never in the publically generated and put on our webpages version).

**Comment by izwick-schachter** [comment]
@ArtOfCode- I think we should make a custom model for this.

**Comment by ArtOfCode-** [comment]
What reasoning, @izwick-schachter?
