### ISSUE TITLE
Reset translation request status after a BCI edit

### ISSUE THREAD

**Issue by ArtOfCode-** [CrowdRescueHQ/SCOT#95]
When a BC item is edited, it should reset the status of its attached translation request so that it's not still marked Completed.

We should also create a new TR status specifically to indicate this state (thanks @izwick-schachter).

**Comment by izwick-schachter** [comment]
@ArtOfCode- We should also making setting this new [Edited] translation request status optional, because sometimes edits don't require re-translation.

**Comment by izwick-schachter** [comment]
See my previous comment

**Comment by ArtOfCode-** [comment]
I'm making it always happen for now, because broadcasters translat

**Comment by izwick-schachter** [comment]
But there's look at the last feature request on the list!

**Comment by ArtOfCode-** [comment]
We can mark that complete too, continuous monitoring on both.

**Comment by izwick-schachter** [comment]
A little "requires retraslation" checkbox can't be that hard...

**Comment by ArtOfCode-** [comment]
No, in terms of code it's not, but the point is that the people editing don't know whether they need to tick it or not, which kinda renders it useless.
