### ISSUE TITLE
Translation request table changes and priority updates

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/SCOT#98]
From @MeghanUX in #73:

> Note the new request has these fields - and they should show up in columns / info on ALL other pages related to this request.
> 
> - Content
> - Source Language
> - Target Language
> - Deliver To
> - Priority
> -  Due Date
> 
> Please change the "Priority" categories to match these (and we need to check with Translation about these definitions) - ALSO - if these categories are changed EVER, they also need to be changed on the other pages as well.
> 
> - 1= Urgent (< 2 hours),
> - 2 = Before Next Broadcast
> - 3= Soon (24 - 48 hours) ,
> - 4= As possible

**Comment by ArtOfCode-** [comment]
Extra columns are [status-declined]. We can change the priority labels, though.
